global:
  slack_api_url: 'https://hooks.slack.com/services/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'

route:
  receiver: 'slack-notifications'

receivers:
  - name: 'slack-notifications'
    slack_configs:
      - channel: '#denis_lebedev'
        send_resolved: true
        title: "{{ range .Alerts }}{{ .Annotations.summary }}\n{{ end }}"
        text: "{{ range .Alerts }}{{ .Annotations.description }}\n{{ end }}"
    email_configs:
      - from: 'markolopes@yandex.ru'
        to: 'markolopes@yandex.ru'
        send_resolved: true
        smarthost: 'smtp.yandex.ru:465'
        auth_username: 'markolopes'
        auth_password: 'Qwe1234$'
        require_tls: false
        headers:
          Subject: "{{ range .Alerts }}{{ .Annotations.summary }}\n{{ end }}"
