version: '3.3'

services:

  mongo:
    image: mongo:${MONGO_VERSION:-3.2}
    volumes:
      - mongo:/data/db
    networks:
      net:

  rabbit:
#    image: pivotalrabbitmq/rabbitmq-prometheus:3.9.0-alpha.221-2020.02.12
#    image: rabbitmq:${RABBITMQ_VERSION:-3-management}
    image: ${PROJECTNAME}/rabbitmq:${RABBITMQ_VERSION:-latest}
    hostname: rabbitmq
    volumes:
      - rabbit:/var/lib/rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_USER:-guest}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASSWORD:-guest}
    ports:
      - ${RABBIT_UI_PUBLISHED_PORT:-15672}:15672  # Порт web интерфейса
      - "15692:15692"
    networks:
      net:

  robot:
    image: ${PROJECTNAME}/robot:${APP_TAG:-latest}
    restart: on-failure
    depends_on:
      - rabbit
      - mongo
    environment:
      - MONGO=${MONGO:-mongo}
      - MONGO_PORT=${MONGO_PORT:-27017}
      - RMQ_HOST=${RMQ_HOST:-rabbit}
      - RMQ_QUEUE=${RMQ_QUEUE:-urls}
      - RMQ_USERNAME=${RABBITMQ_USER:-guest}
      - RMQ_PASSWORD=${RABBITMQ_PASSWORD:-guest}
      - CHECK_INTERVAL=${CHECK_INTERVAL:-10}
      - EXCLUDE_URLS=${EXCLUDE_URLS:-.*github.com,.*twitter.com}
    command:
      - ${URLS:-https://vitkhab.github.io/search_engine_test_site/}
    ports:
      - ${ROBOT_PUBLISHED_PORT:-8001}:8000
    networks:
      net:

  ui:
    image: ${PROJECTNAME}/ui:${APP_TAG:-latest}
    restart: on-failure
    depends_on:
      - mongo
    environment:
      - MONGO=${MONGO:-mongo}
      - MONGO_PORT=${MONGO_PORT:-27017}
    ports:
      - ${UI_PUBLISHED_PORT:-8000}:8000
    networks:
      net:

volumes:
  mongo:
  rabbit:

networks:
  net:
    ipam:
      config:
        - subnet: ${NET:-10.0.1.0/24}
