version: '3.3'

services:

  prometheus:
    image: ${PROJECTNAME}/prometheus:${PROMETHEUS_VERSION:-latest}
    volumes:
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention=1d'
    networks:
      net:
    ports:
      - '9090:9090'


  node-exporter:
    image: prom/node-exporter:v0.15.2
    user: root
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.ignored-mount-points="^/(sys|proc|dev|host|etc)($$|/)"'
    networks:
      net:


  mongodb-exporter:
    image: ${PROJECTNAME}/mongodb-exporter:${MONGODB_EXPORTER_VERSION:-latest}
    command:
      - '--collect.database'
      - '--collect.collection'
      - '--collect.topmetrics'
      - '--collect.indexusage'
      - '--collect.connpoolstats'
      - '--mongodb.uri=mongodb://mongo:27017'
    networks:
      net:


  blackbox-exporter:
    image: prom/blackbox-exporter:${BLACKBOX_EXPORTER_VERSION:-v0.16.0}
    networks:
      net:


  cadvisor:
    image: google/cadvisor:v0.29.0
    volumes:
      - '/:/rootfs:ro'
      - '/var/run:/var/run:rw'
      - '/sys:/sys:ro'
      - '/var/lib/docker/:/var/lib/docker:ro'
    ports:
      - '8080:8080'
    networks:
      net:


  grafana:
    image: ${PROJECTNAME}/grafana:${GRAFANA_VERSION:-latest}
    volumes:
      - grafana_data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=secret
    depends_on:
      - prometheus
    ports:
      - 3000:3000
    networks:
      net:


  alertmanager:
    image: ${PROJECTNAME}/alertmanager:${ALERTMANAGER_VERSION:-latest}
    command:
      - '--config.file=/etc/alertmanager/config.yml'
      - '--storage.path=/alertmanager'
    ports:
      - 9093:9093
    networks:
      net:


volumes:
  prometheus_data:
  grafana_data:

networks:
  net:
    ipam:
      config:
        - subnet: ${NET:-10.0.1.0/24}
