version: '3.3'

services:

  prometheus:
    image: ${PROJECTNAME}/prometheus:${PROMETHEUS_VERSION:-latest}
    volumes:
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention=1d'
    networks:
      net:
    ports:
      - ${PROMETHEUS_PUBLISHED_PORT:-9090}:9090/tcp


  grafana:
    image: ${PROJECTNAME}/grafana:${GRAFANA_VERSION:-latest}
    volumes:
      - grafana_data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=secret
    depends_on:
      - prometheus
    ports:
      - ${GRAFANA_PUBLISHED_PORT:-3000}:3000/tcp
    networks:
      net:


  alertmanager:
    image: ${PROJECTNAME}/alertmanager:${ALERTMANAGER_VERSION:-latest}
    command:
      - '--config.file=/etc/alertmanager/config.yml'
      - '--storage.path=/alertmanager'
    ports:
      - ${ALERTMANAGER_PUBLISHED_PORT:-9093}:9093/tcp
    networks:
      net:


volumes:
  prometheus_data:
  grafana_data:

networks:
  net:
    ipam:
      config:
        - subnet: ${NET:-10.0.1.0/24}
